# Use official Python image
FROM python:3.11

# Set working directory inside container
WORKDIR /app

# Copy everything from current directory to /app in container
COPY . /app

# Install dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN apt install fonts-dejavu-core
